### ISSUE TITLE
Error on Instalation

### ISSUE THREAD

**Issue by dornelas** [sysrpl/Lazarus.WebBrowser#1]
I got error on instalation process:

> Compile package WebBrowser 0.0: Exit code 256, Errors: 2
> websystem.pas(23,41) Error: Identifier not found "T"
> websystem.pas(24,30) Error: Identifier not found "T"

Versions:
fpc 3.0.4-3
fpc-src 3.0.4-1
lazarus 1.8.4-1
lazarus-qt5 1.8.4-1
gdb 8.1-1
gdb-common 8.1-1

**Comment by freesoftwarewiz** [comment]
I had the same issue as dornelas  on installation. Am wondering if this project has been abandoned? Does not appear to have been touched since being put up back in April. The getlazarus.org forums aren't responsive either.

Joe C.

**Comment by TB1234** [comment]
I have got the same problem here...

You can comment out the two functions. But then a WebInspector class is not found. So i think this component is not complete and garbage...

**Comment by expertup** [comment]
White install I have these error:
```
websystem.pas(547,26) Warning: function result variable of a managed type does not seem to be initialized
webbrowserctrls.pas(431,14) Error: Identifier not found "WebInspectorNew"
webbrowserctrls.pas(879,40) Error: Identifier not found "WebInspectorWSClass"
```
